### ISSUE TITLE
Any plan to support HTTP live streaming aka HLS?

### ISSUE THREAD

**Issue by faywong** [joanpuigsanz/servdroid#12]
Hi Buddy,

"servdroid" serve HTML pages well.
I verified that the HLS can't be supported on version 0.2.6.

So is there any plan to support HLS in it?

Thanks,
fay

**Comment by joanpuigsanz** [comment]
It is true that is not implemented, but I think that it is a good idea. Right now I don't have that much time, so if you could help with that it will be awesome :)

**Comment by faywong** [comment]
OK. Thanks for clarifying.
