### ISSUE TITLE
`mServiceHelper.getServiceController()` always return null

### ISSUE THREAD

**Issue by Ovilia** [joanpuigsanz/servdroid#13]
Hi, I found `mServiceHelper.getServiceController()` always return `null` when I try to build a simple app according to README. It seems `onServiceConnected` is never called in https://github.com/joanpuigsanz/servdroid/blob/ef738242a56661a81790b5feff46d6aaeb2396a0/android/ServDroid.web/src/org/servDroid/helper/ServiceHelper.java#L62 

Any idea?

**Comment by joanpuigsanz** [comment]
Do you call  mServiceHelper.connect(); and configured your manifest properly?
