### ISSUE TITLE
How to start server automatically  when app starts.

### ISSUE THREAD

**Issue by Saurav-Suman** [joanpuigsanz/servdroid#14]

**Comment by joanpuigsanz** [comment]
You can start the server when the system boots or when is connected to a wifi network

**Comment by Saurav-Suman** [comment]
i want to start server when app open (without clicks on toggle button) means- i want to remove toggle button from app interface.

**Comment by joanpuigsanz** [comment]
In thT case you will need to change the source code

**Comment by Saurav-Suman** [comment]
DOne
